name: homi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  sqflite:
  http: ^0.13.3
  fluttertoast: ^8.0.6
  shared_preferences: ^2.0.6
  page_transition: ^2.0.2
  line_icons: ^2.0.1
  ionicons: ^0.1.2
  recase: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  permission_handler: ^8.3.0
  http_parser: any
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.10
  dio: ^4.0.4
  iconsax: ^0.0.8
  easy_dynamic_theme: ^2.2.0
  day_night_switcher: ^0.2.0+1
  linkfy_text: ^1.1.5
  device_info: any
  share: ^2.0.4
  introduction_screen: ^2.1.0
  pull_to_refresh: ^2.0.0
  carrier_info: ^2.0.5
  image_picker: ^0.8.3+2
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  flutter_linkify: ^5.0.2
  carousel_slider: ^4.0.0
  video_box: 0.16.0
  country_code_picker: ^2.0.2
  country_calling_code_picker: ^2.0.0
  flutter_switch: ^0.3.2
  file_picker: ^4.2.2+1
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.9
  gallery_saver: ^2.3.2
  google_sign_in: ^5.3.1
  sign_in_with_apple: ^4.0.0
  provider: ^6.0.1
  percent_indicator: ^4.0.0
  wakelock: ^0.6.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Home.png
    - assets/images/Profile.png
    - assets/images/Doctors.png
    - assets/images/Pharmacy.png
    - assets/images/Community.png
    - assets/images/Group.png
    - assets/images/search.png
    - assets/images/loc.png
    - assets/images/Headache.png
    - assets/images/Supplements.png
    - assets/images/Infants.png
    - assets/images/Panadol.png
    - assets/images/Doliprane.png
    - assets/images/Paracetamol-200.png
    - assets/images/Ibuprofen-200.png
    - assets/images/Paracetamol-400.png
    - assets/images/Ibuprofen-400.png
    - assets/images/back_arrow.png
    - assets/images/cart.png
    - assets/images/Cough.png
    - assets/images/404.png
    - assets/images/fav.png
    - assets/images/none.png
    - assets/images/pack-size.png
    - assets/images/product-id.png
    - assets/images/constituents.png
    - assets/images/dispense.png
    - assets/images/add-to-cart.png
    - assets/images/down.png
    - assets/images/remove.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/pabi at ledge.jpg
    - assets/images/Homi-logo-white.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaAltBold
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Alt Bold.otf
    - family: ProximaAltLight
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Alt Light.otf
    - family: ProximaAltThin
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Alt Thin.otf
    - family: ProximaBlack
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Black.otf
    - family: ProximaBold
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Bold.otf
    - family: ProximaExtraBold
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Extrabold.otf
    - family: ProximaAltSemiBold
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Semibold.otf
    - family: ProximaThin
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Thin.otf
    - family: ProximaRegular
      fonts:
        - asset: assets/fonts/Proxima Nova/ProximaNova-Regular.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
